version: '3.5'

services:


###############################################################################
# API - Node Application
###############################################################################
  hobb-api:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: 
      registry.io.bb.com.br:3389/hobb/api:latest
    container_name: hobb-api
    command: nodemon --inspect=0.0.0.0:5858 /var/app/api.js
    ports:
      - '3443:3443'
      - '5858:5858'
    volumes:
      - ./src/:/var/app
    environment:
      - MONGO_URL=mongodb://hobb-db:27017/hobb
      - MONGO_USER=admin
      - MONGO_PWD=admin
      - API_PORT=3443
      - KERNEL_AUTHORIZATION=7egQpg76YVH1YSkdUpzJL8MIbafZ2DJQ6AMFHV6n
      - KERNEL_ACCOUNT=https://api.kernel.io.bb.com.br/v0/accounts


###############################################################################
# Mongo - Banco de Dados
###############################################################################
  hobb-db:
    image: mongo:3.6.6
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'
    environment: 
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

###############################################################################
# mongo-express - Web-based MongoDB admin interface
###############################################################################
  mongo-express:
    image: mongo-express:0.45.0
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: hobb-db
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    ports:
      - '8081:8081'

###############################################################################
# Networks config
###############################################################################
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.5.0/24

###############################################################################
# Volumes
###############################################################################
# to remove all: docker volume rm $(docker volume ls -q)
volumes:
  mongo_data:

