version: '3.5'

services:

###############################################################################
# Mongo - Banco de Dados
###############################################################################
  hobb-db:
    container_name: 
      hobb-db
    image: 
      mongo:4.0.2
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

###############################################################################
# API - Node Application
###############################################################################
  hobb-api:
    container_name: 
      hobb-api   
    build: 
      context: .
      dockerfile: 
        Dockerfile       
    image: 
      registry.io.bb.com.br:3389/hobb/api:latest
    ports:
      - 3443:3443
    environment:
      - MONGO_URL=mongodb://hobb-db:27017/hobb
      - MONGO_USER=admin
      - MONGO_PWD=admin
      - API_PORT=3443
      - KERNEL_AUTHORIZATION=7egQpg76YVH1YSkdUpzJL8MIbafZ2DJQ6AMFHV6n
      - KERNEL_ACCOUNT=https://api.kernel.io.bb.com.br/v0/accounts

###############################################################################
# Mocha - Integration Test
###############################################################################
  hobb-api-test:
    container_name: 
      hobb-api-test
    build: 
      context: .
      dockerfile: Dockerfile-test
    ports:
      - '3001:3443'
    environment:
      - MONGO_HOST=hobb-db
      - MONGO_PORT=27017
      - MONGO_URL=mongodb://hobb-db:27017/test  
      - MONGO_PWD=admin
      - MONGO_USER=admin  
      - KERNEL_AUTHORIZATION=7egQpg76YVH1YSkdUpzJL8MIbafZ2DJQ6AMFHV6n
      - KERNEL_ACCOUNT=https://api.kernel.io.bb.com.br/v0/accounts


# Networks config
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.5.0/24

# Volume default docker
# remove all: docker volume rm $(docker volume ls -q)
volumes:
  mongo_data:
