apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-exporter
  namespace: hobb-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-exporter
  template:
    metadata:
      labels:
        app: mongodb-exporter
    spec:
      containers:
      - name: mongodb-exporter-container
        image: targetprocess/mongodb_exporter:latest
        args: ["-mongodb.uri=mongodb://admin:admin@hobb-api-mongodb:27017/hobb", "-mongodb.collect.oplog=false", "-mongodb.collect.replset=false"]
        ports:
        - containerPort: 9001
          name: service
        # env:
        # - name:  MONGODB_URL
        #   value: "mongodb://admin:admin@hobb-api-mongodb:27017/hobb" 
        # - name:  HTTP_AUTH
        #   value: "admin:admin"
